### ISSUE TITLE
how to install ffmpeg ? 

### ISSUE THREAD

**Issue by xNeizy** [Maks-gaming/mineflayer-plasmovoice#14]
How to install ffmpeg, just throw to the folder with project or are there other ways ?

**Comment by xNeizy** [comment]
I installed FFmpeg this way: downloaded from the official website ffmpeg.org archive for my operating system. I threw the ffmpeg folder on the way C:\FFmpeg , and also in the change of environment parameters specified the path to C:\FFmpeg\bin . But now he writes an error: Error: FFmpeg is not installed

![image](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/89652352/43e81f31-7fcd-414e-8fcb-56fc192c8c7d)
![image](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/89652352/e23b5adf-e74a-4a19-a7aa-2a02d9c1ea02)
![image](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/89652352/52802c06-51b8-4bb2-82dd-ef16fd15507f)

**Comment by Maks-gaming** [comment]
the main thing is that ffmpeg is in the environment of the operating system, there is information about the installation on the Internet, and I also ask you not to open a new issue for each question.

**Comment by xNeizy** [comment]
And how can I ask questions differently ?

**Comment by Maks-gaming** [comment]
in the first issue? =P

**Comment by xNeizy** [comment]
I didn't get an answer from you xD
![image](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/89652352/06c66fee-eb53-49fd-8269-3a7311303d6f)

**Comment by Maks-gaming** [comment]
you just had to wait, and so I installed ffmpeg through choco

**Comment by xNeizy** [comment]
ok, now this is my last topic, from now on I will ask questions here

**Comment by xNeizy** [comment]
I wrote this code, now there seems to be no error, but the bot still does not speak, but just sits...

```
const mineflayer = require("mineflayer")
const plasmo = require("mineflayer-plasmovoice")

const bot = mineflayer.createBot({
    "host": "localhost"
})

bot.loadPlugin(plasmo.plugin)

bot.on("voicechat_connected", () => {
    bot.setControlState("sneak", true)

    // Path to file with any audio format
    bot.plasmovoice.SendAudio("music.mp3")
})

bot.on("voicechat_audio_end", () => {
    bot.setControlState("sneak", false)
})

bot.on('chat', (username, message) => {
    if (username === 'dvdentum' && message.includes('play')) {
        bot.setControlState("sneak", true)

        // Path to file with any audio format
        bot.plasmovoice.sendAudio("music.mp3")
        bot.chat('OK?')
    }
})
```
![2023-07-29_12 02 51](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/89652352/2270531d-7d04-485f-b436-a30e34180478)

**Comment by Maks-gaming** [comment]
enable debug (check readme.md)

**Comment by xNeizy** [comment]
![image](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/89652352/20ca8095-b52b-4e8d-bb1e-4c5b3df9f7da)
Cool, I added this piece of code to the end of my code: 

```
bot.on("login", () => {
    bot.plasmovoice.enableDebug();
})
```

**Comment by xNeizy** [comment]
maybe the problem is not in me, but in the library?

**Comment by Maks-gaming** [comment]
which lib version are you using

**Comment by xNeizy** [comment]
![image](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/89652352/e3e1bfc8-3510-44d8-ac05-22f480844721)

**Comment by Maks-gaming** [comment]
> ![image](https://user-images.githubusercontent.com/89652352/256977352-e3e1bfc8-3510-44d8-ac05-22f480844721.png)

run `npm install mineflayer-plasmovoice@1.1.3a`

**Comment by xNeizy** [comment]
YEEAAH

**Comment by xNeizy** [comment]
why is audio playing with some interruptions ? I think because my computer resources are not enough, maybe :)

**Comment by xNeizy** [comment]
Although, I think 4 cores, 10 GB, should be enough

**Comment by Maks-gaming** [comment]
it is possible, but so far the sending of the stream is not very well implemented, so there may be interference.

**Comment by xNeizy** [comment]
Interference can be insignificant, and sometimes significant, but it's still cool!

**Comment by Maks-gaming** [comment]
no problem)

**Comment by xNeizy** [comment]
The song didn't play for long... After some repetitions, an error pops up:
![image](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/89652352/348514f5-5fd0-4f9e-adce-95278616b957)

**Comment by xNeizy** [comment]
For some reason, the bot does not play the file for ~ 48 seconds... Although it lasts 1 minute 48 seconds, but the sending of packets continues...

**Comment by Maks-gaming** [comment]
> For some reason, the bot does not play the file for more than 48 seconds... Although the track lasts 1 minute 48 seconds, but the sending of packets continues...
ikr, I don't know how to fix it rn

**Comment by xNeizy** [comment]
the bot produces music according to its mood, when you want to play the same track for 48 seconds, and when you want the whole track xD
