### ISSUE TITLE
the bot does not speak!

### ISSUE THREAD

**Issue by ZERO28822** [Maks-gaming/mineflayer-plasmovoice#68]
**### I've installed everything I need. I took an example of your code and ran it, but for some reason there is an icon above the bot's head (photo attached). Please help me!!!**
![Снимок экрана 2024-05-03 205858](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/155769483/8d02b305-7b26-42f9-8b17-a9aec6b617a9)
**Also here is the code I used:** 
const mineflayer = require('mineflayer');
const plasmo = require('mineflayer-plasmovoice');

const bot = mineflayer.createBot({
  port: 57873,
  host: '', 
  username: '',
  version: '1.16.5',
});

bot.loadPlugin(plasmo.plugin)

bot.on("plasmovoice_connected", () => {
  bot.setControlState("sneak", true)

  // Path to file with any audio format
  bot.plasmovoice.sendAudio("C:\\Users\\fdewf\\misc\\1.mp3")
})

bot.on("plasmovoice_audio_end", () => {
  bot.setControlState("sneak", false)
})
bot.on("login", () => {
  bot.plasmovoice.enableDebug();
})

**Comment by Maks-gaming** [comment]
send me debug logs first

**Comment by ZERO28822** [comment]
**I hope this is what you nee
![Снимок экрана 2024-05-04 115159](https://github.com/Maks-gaming/mineflayer-plasmovoice/assets/155769483/7db45fac-0bbc-448f-b97f-f9022080c8f0)
d.** **The fact is that the debug log is empty and there are no errors in it!**

**Comment by Maks-gaming** [comment]
I can't help you, this shouldn't happen, or you're giving me too few details
